


quiz_questions = [

        ['What is the output of print(type(10))?', ['int', 'float', 'str', 'type'], 0],
        ['Which keyword is used to define a function in Python?', ['func', 'define', 'def', 'function'], 2],
        ['Which data type is used to store text?', ['int', 'str', 'list', 'tuple'], 1],
        ['What is the output of print(2 + 3 * 2)?', ['10', '12', '8', '7'], 2],
        ['Which symbol is used for comments in Python?', ['//', '#', '/* */', '--'], 1],
        ['What is the output of print(len("Python"))?', ['5', '6', '7', 'Error'], 1],
        ['Which of these is a list?', ['(1,2,3)', '{1,2,3}', '[1,2,3]', '<1,2,3>'], 2],
        ['Which function is used to take input?', ['get()', 'input()', 'scan()', 'read()'], 1],
        ['What is the output of print(10//3)?', ['3.3', '3', '4', '3.0'], 1],
        ['Which operator is used for exponent?', ['^', '**', '//', '%%'], 1],
        ['What is the output of print(5/2)?', ['2', '2.5', '3', 'Error'], 1],
        ['Which keyword is used for loop?', ['loop', 'for', 'iterate', 'repeat'], 1],
        ['Which data type is immutable?', ['list', 'dict', 'set', 'tuple'], 3],
        ['What is the output of print(bool(0))?', ['True', 'False', '0', 'Error'], 1],
        ['Which function converts string to integer?', ['str()', 'int()', 'float()', 'chr()'], 1],
        ['Which keyword is used for conditional?', ['if', 'when', 'case', 'check'], 0],
        ['What is the output of print(5%2)?', ['2', '3', '1', '0'], 2],
        ['Which collection is unordered?', ['list', 'tuple', 'set', 'string'], 2],
        ['What is the output of print(type([]))?', ['list', 'dict', 'tuple', 'set'], 0],
        ['Which keyword is used to exit loop?', ['stop', 'break', 'exit', 'end'], 1],
        ['Which function gives range of numbers?', ['range()', 'list()', 'span()', 'loop()'], 0],
        ['What is slicing?', ['Copying list', 'Extracting part', 'Deleting', 'Sorting'], 1],
        ['What is the output of print("a"*3)?', ['aaa', 'a3', 'error', '3a'], 0],
        ['Which keyword is used for else if?', ['elseif', 'elif', 'else if', 'ifelse'], 1],
        ['Which function returns length?', ['count()', 'size()', 'len()', 'length()'], 2],
        ['What is the output of print(10==10)?', ['True', 'False', '10', 'Error'], 0],
        ['Which operator is logical AND?', ['&&', 'and', '&', '&&&'], 1],
        ['Which type is used for key-value?', ['list', 'tuple', 'dict', 'set'], 2],
        ['Which method adds element to list?', ['add()', 'insert()', 'append()', 'push()'], 2],
        ['What is output of print(type({}))?', ['set', 'dict', 'list', 'tuple'], 1],
        ['Which keyword defines class?', ['object', 'class', 'define', 'struct'], 1],
        ['Which keyword is used to import module?', ['include', 'import', 'using', 'require'], 1],
        ['Which function converts to float?', ['int()', 'float()', 'str()', 'chr()'], 1],
        ['What is output of print(bool(""))?', ['True', 'False', 'None', 'Error'], 1],
        ['Which operator checks equality?', ['=', '==', '!=', '>='], 1],
        ['Which structure stores unique values?', ['list', 'tuple', 'set', 'dict'], 2],
        ['Which method removes last list element?', ['delete()', 'remove()', 'pop()', 'clear()'], 2],
        ['What is output of print(2**3)?', ['6', '8', '9', '5'], 1],
        ['Which function returns ASCII value?', ['chr()', 'ord()', 'ascii()', 'val()'], 1],
        ['Which method converts list to string?', ['join()', 'split()', 'merge()', 'concat()'], 0],
        ['What is lambda function?', ['Named function', 'Anonymous function', 'Loop', 'Class'], 1],
        ['Which keyword is used for exception handling?', ['try', 'catch', 'error', 'final'], 0],
        ['Which block always executes?', ['try', 'except', 'finally', 'else'], 2],
        ['What does map() return?', ['list', 'tuple', 'iterator', 'set'], 2],
        ['Which function filters elements?', ['map()', 'filter()', 'reduce()', 'select()'], 1],
        ['What is list comprehension?', ['Loop', 'Short syntax', 'Class', 'Function'], 1],
        ['Which keyword creates generator?', ['yield', 'return', 'gen', 'produce'], 0],
        ['Which module handles OS operations?', ['sys', 'os', 'math', 'random'], 1],
        ['Which module generates random numbers?', ['math', 'random', 'sys', 'os'], 1],
        ['What is recursion?', ['Loop', 'Function calling itself', 'Class', 'Condition'], 1],
        ['Which method sorts list?', ['sort()', 'arrange()', 'order()', 'set()'], 0],
        ['Which method returns reversed list?', ['reverse()', 'sort()', 'flip()', 'rev()'], 0],
        ['What is dictionary key type?', ['mutable', 'immutable', 'list', 'set'], 1],
        ['Which keyword deletes variable?', ['remove', 'del', 'delete', 'clear'], 1],
        ['Which function returns max value?', ['max()', 'high()', 'top()', 'big()'], 0],
        ['Which function returns min value?', ['min()', 'low()', 'small()', 'less()'], 0],
        ['Which method clears list?', ['delete()', 'remove()', 'clear()', 'pop()'], 2],
        ['Which method copies list?', ['clone()', 'copy()', 'duplicate()', 'mirror()'], 1],
        ['Which keyword is used for inheritance?', ['extends', 'inherit', 'class', 'super'], 2],
        ['What is __init__?', ['Constructor', 'Destructor', 'Loop', 'Variable'], 0],
        ['Which function converts int to string?', ['str()', 'int()', 'float()', 'chr()'], 0],
        ['Which operator is logical OR?', ['||', 'or', '|', '&&'], 1],
        ['Which function returns length of list?', ['count()', 'size()', 'len()', 'length()'], 2],
        ['Which keyword is used for pass statement?', ['skip', 'pass', 'continue', 'next'], 1],
        ['Which keyword skips iteration?', ['break', 'continue', 'pass', 'stop'], 1],
        ['Which function returns type?', ['type()', 'typeof()', 'kind()', 'class()'], 0],
        ['Which structure allows duplicates?', ['set', 'list', 'dict', 'none'], 1],
        ['Which method inserts at position?', ['add()', 'append()', 'insert()', 'push()'], 2],
        ['Which function converts to list?', ['list()', 'set()', 'dict()', 'tuple()'], 0],
        ['Which function converts to tuple?', ['tuple()', 'list()', 'set()', 'dict()'], 0],
        ['Which is mutable?', ['tuple', 'string', 'list', 'int'], 2],
        ['Which is immutable?', ['list', 'set', 'tuple', 'dict'], 2],
        ['Which keyword defines generator?', ['yield', 'return', 'gen', 'lambda'], 0],
        ['Which method removes specific element?', ['pop()', 'remove()', 'delete()', 'discard()'], 1],
        ['Which method removes element from set?', ['remove()', 'pop()', 'discard()', 'both A and C'], 3],
        ['Which function sums elements?', ['add()', 'sum()', 'total()', 'plus()'], 1],
        ['Which module handles system?', ['sys', 'os', 'math', 'time'], 0],
        ['Which method joins strings?', ['join()', 'merge()', 'concat()', 'combine()'], 0],
        ['Which method splits string?', ['split()', 'divide()', 'break()', 'cut()'], 0],
        ['Which keyword handles errors?', ['try', 'fix', 'solve', 'debug'], 0],
        ['What is the output of print(3*3**2)?', ['81', '27', '18', '36'], 1],
        ['Which function returns absolute value?', ['abs()', 'absolute()', 'mod()', 'fabs()'], 0],
        ['Which keyword is used to create anonymous function?', ['def', 'lambda', 'func', 'anon'], 1],
        ['Which data type is ordered and immutable?', ['list', 'set', 'tuple', 'dict'], 2],
        ['Which operator is floor division?', ['/', '//', '%', '**'], 1],
        ['Which keyword is used to handle multiple exceptions?', ['except', 'multi', 'catch', 'try'], 0],
        ['What is output of print(bool("False"))?', ['False', 'True', 'Error', 'None'], 1],
        ['Which function rounds number?', ['round()', 'approx()', 'ceil()', 'floor()'], 0],
        ['Which module is used for date?', ['time', 'datetime', 'calendar', 'clock'], 1],
        ['Which method finds substring?', ['search()', 'find()', 'index()', 'both B and C'], 3],
        ['Which keyword creates iterator?', ['iter', 'yield', 'next', 'loop'], 0],
        ['Which function returns next item?', ['next()', 'get()', 'fetch()', 'item()'], 0],
        ['Which keyword is used to define block?', ['{}', 'indent', 'begin', 'end'], 1],
        ['Which function converts to set?', ['set()', 'list()', 'tuple()', 'dict()'], 0],
        ['Which method removes all elements from dict?', ['clear()', 'remove()', 'delete()', 'pop()'], 0],
        ['Which function evaluates expression?', ['eval()', 'exec()', 'run()', 'calc()'], 0],
        ['Which function executes code string?', ['eval()', 'exec()', 'run()', 'code()'], 1],
        ['Which keyword is used for global variable?', ['global', 'var', 'public', 'static'], 0],
        ['Which keyword is used for local variable?', ['local', 'var', 'none', 'no keyword'], 3],
        ['Which operator checks membership?', ['in', 'inside', 'has', 'exist'], 0],
        ['Which operator checks identity?', ['==', 'is', 'equals', 'same'], 1],
        ['Which method adds key to dict?', ['add()', 'insert()', 'assignment', 'append()'], 2],
        ['Which function returns all keys?', ['keys()', 'getkeys()', 'keylist()', 'list()'], 0],
        ['Which function returns all values?', ['values()', 'getvalues()', 'val()', 'list()'], 0],
        ['Which function returns key-value pairs?', ['items()', 'pairs()', 'both', 'dict()'], 0],
        ['Which keyword defines abstract class?', ['abstract', 'abc', 'class', 'base'], 1],
        ['Which module supports regex?', ['regex', 're', 'pattern', 'match'], 1],
        ['Which method matches pattern?', ['match()', 'search()', 'find()', 'both A and B'], 3],
        ['Which keyword is used in loop else?', ['else', 'end', 'after', 'finish'], 0],
        ['Which method strips whitespace?', ['trim()', 'strip()', 'remove()', 'clean()'], 1],
        ['Which method converts to uppercase?', ['upper()', 'uppercase()', 'cap()', 'big()'], 0],
        ['Which method converts to lowercase?', ['lower()', 'small()', 'lowercase()', 'down()'], 0],
        ['Which method replaces string?', ['replace()', 'change()', 'swap()', 'edit()'], 0],
        ['Which method counts substring?', ['count()', 'find()', 'search()', 'match()'], 0],
        ['Which function opens file?', ['open()', 'file()', 'read()', 'write()'], 0],
        ['Which mode is for reading file?', ['r', 'w', 'a', 'x'], 0],
        ['Which mode is for writing file?', ['r', 'w', 'a', 'x'], 1],
        ['Which mode appends file?', ['r', 'w', 'a', 'x'], 2],
        ['Which function reads file?', ['read()', 'write()', 'open()', 'close()'], 0],
        ['Which function closes file?', ['end()', 'close()', 'stop()', 'exit()'], 1],
        ['Which keyword is used for context manager?', ['use', 'with', 'manage', 'open'], 1],
        ['Which function checks file exists?', ['exists()', 'isfile()', 'os.path.exists()', 'check()'], 2],
        ['Which module handles JSON?', ['json', 'js', 'data', 'file'], 0],
        ['Which function parses JSON?', ['load()', 'loads()', 'parse()', 'read()'], 1],
        ['Which function writes JSON?', ['dump()', 'dumps()', 'write()', 'save()'], 0],
        ['Which function converts object to string JSON?', ['dump()', 'dumps()', 'write()', 'convert()'], 1],
        ['Which module handles time?', ['time', 'clock', 'timer', 'datetime'], 0],
        ['Which function delays execution?', ['wait()', 'sleep()', 'delay()', 'hold()'], 1]

]
